#!/bin/sh

set -e

lb config noauto \
	--architectures i386 \
	--distribution "jessie" \
	--archive-areas "main contrib" \
	--iso-application "LibraZiK studio audio - #1 premier pas" \
	--iso-preparer "LibraZiK studio audio - trebmuh; http://librazik.tuxfamily.org/; trebmuh@tuxfamily.org" \
	--iso-publisher "LibraZiK studio audio; http://librazik.tuxfamily.org/; trebmuh@tuxfamily.org" \
	--iso-volume "LibraZiK studio #1 premier pas" \
	--bootappend-live "boot=live components quiet silent hostname=LibraZiK-studio-audio locales=fr_FR.UTF-8 keyboard-layouts=fr" \
	--debian-installer live \
	--memtest memtest86+ \
	--mirror-bootstrap "http://deb.debian.org/debian/" \
	--mirror-binary "http://deb.debian.org/debian/" \
	--mirror-chroot "http://deb.debian.org/debian/" \
	--mirror-binary-security "http://deb.debian.org/debian-security/" \
	--mirror-chroot-security "http://deb.debian.org/debian-security/" \
	--backports "true" \
	--updates "true" \
	--security "true" \
	"${@}"

