#!/bin/sh

# Fichier de configuration pour la construction d'un live LibraZiK-4 64 bits en anglais
# Ce fichier a été écrit par Olivier Humbert pour le projet studio audio LibraZiK 
# Licence : GNU-GPL-3

# Configuration file for building a 64-bit LibraZiK-4 english live
# This file has been written by Olivier Humbert for the LibraZiK audio studio project
# License: GNU-GPL-3

# Copyright : Olivier Humbert <trebmuh@tuxfamily.org> 2015-2023
# https://librazik.tuxfamily.org

set -e

lb config noauto \
	--apt-recommends true \
	--apt-secure true \
	--apt-source-archives true \
	--archive-areas "main contrib" \
	--backports true \
	--binary-images iso-hybrid \
	--bootappend-live "boot=live components quiet silent hostname=LibraZiK4-studio-audio" \
	--bootloaders syslinux \
	--clean \
	--color \
	--debian-installer live \
	--debian-installer-gui true \
	--distribution bullseye \
	--iso-application "LibraZiK-4 studio audio - #4 barbe à papas" \
	--iso-preparer "LibraZiK studio audio - trebmuh; https://librazik.tuxfamily.org/; trebmuh@tuxfamily.org" \
	--iso-publisher "LibraZiK studio audio; https://librazik.tuxfamily.org/; trebmuh@tuxfamily.org" \
	--iso-volume "LibraZiK stud #4 barbe à papas" \
	--mirror-binary "http://deb.debian.org/debian/" \
	--mirror-binary-security "http://deb.debian.org/debian-security/" \
	--mirror-bootstrap "http://deb.debian.org/debian/" \
	--mirror-chroot "http://deb.debian.org/debian/" \
	--mirror-chroot-security "http://deb.debian.org/debian-security/" \
	--security true \
	--source false \
	--uefi-secure-boot auto \
	--updates true \
	"${@}"

